### ISSUE TITLE
The resolution about KITTI Dataset

### ISSUE THREAD

**Issue by Rolandxx7** [cv-rits/rain-rendering#19]
Dear author,
 
Thanks for your great contribution. I have a question that how to restore the resolution of the rainy KITTI dataset you generated back to the resolution of the original KITTI dataset, or could you please send me the original resolution version of the data?

**Comment by rdecharette** [comment]
Hello @Rolandxx7,

thanks. I I replied yesterday but forgot to submit, my bad.
About your original issue: The KITTI images were crop-centered because depth generation for KITTI uses Monodepth or Spaded (https://arxiv.org/pdf/1808.00769.pdf) which outputs 1216x352 depth maps. Weather augmentation can only be computed where depth is defined.
You can easily compare with other methods by applying a 1216x352 crop-center on KITTI images.

The best way to augment original resolution of KITTI images, would be to apply any monocular depth and use that to render rain/fog again following readme. Their might be a few stuff to adjust but that should be simple.
A dirty workaround is to copy paste our weather-augmentation in the center of original KITTI images, but that will inevitably leave a thin visible surface (1242x375 minus 1216x352) with no augmentation.. Not the best.

Hope that helps.

**Comment by Rolandxx7** [comment]
> 

Thanks for your kind reply!
For the best way, how should I find a depth map of the same resolution as the original KITTI dataset? Because the size of KITTI's depth map is always smaller than the original image.

**Comment by Rolandxx7** [comment]
> Hello @Rolandxx7,
> 
> thanks. I I replied yesterday but forgot to submit, my bad. About your original issue: The KITTI images are smaller than original resolution because our augmentation on KITTI uses depth maps generated with Monodepth or Spaded (https://arxiv.org/pdf/1808.00769.pdf) which are 1216x352 crop-centered. Weather augmentation can only be computed where depth is defined. You can easily compare with other methods by applying a 1216x352 crop-center on KITTI images.
> 
> The best way to augment original resolution of KITTI images, would be to apply any monocular depth and use that to render rain/fog again following readme. Their might be a few stuff to adjust but that should be simple. A dirty workaround is to copy paste our weather-augmentation in the center of original KITTI images, but that will inevitably leave a thin visible surface (1242x375 minus 1216x352) with no augmentation.. Not the best.
> 
> Hope that helps.

Thanks for your kind reply!
For the best way, how should I find a depth map of the same resolution as the original KITTI dataset? Because the size of KITTI's depth map is always smaller than the original image.

**Comment by rdecharette** [comment]
Most depth inference are smaller than original KITTI resolution, usually people just crop-center as we did. 
However, there are full-size options. You can refer to https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion and choose the best open-code version. It seems https://github.com/cvpr2022-dc/code_11438 is full size. Depth will be slighly worse than with our Spaded since we use Lidar input, but it should not affect much rain/fog realism.

**Comment by Rolandxx7** [comment]
> Most depth inference are smaller than original KITTI resolution, usually people just crop-center as we did. However, there are full-size options. You can refer to https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion and choose the best open-code version. It seems https://github.com/cvpr2022-dc/code_11438 is full size. Depth will be slighly worse than with our Spaded since we use Lidar input, but it should not affect much rain/fog realism.

Sorry to bother again, The original resolution of KITTI image is 1242×375, and you used the crop-centered method. If I copy paste your weather-augmentation in the center of original KITTI images, there's going to be a bias, because 375 is not divisible by 2. So I would like to know how to solve this problem.

**Comment by rdecharette** [comment]
No problem, the crop-center code used is here: https://github.com/cv-rits/rain-rendering/blob/6365f2077764320f0a1bd5244eda2a5489225230/common/my_utils.py#L88-L96 there is a floor indeed
Good luck.
